### ISSUE TITLE
Fix remote shares access with GVFS 1.48

### ISSUE THREAD

**Issue by x80486** [flathub/org.gnome.FileRoller#10]
Reference: https://github.com/flathub/flathub/issues/2180

**Comment by A6GibKm** [comment]
I am not sure of what is fixed by adding that flag as I don't quite understand GVFS. Care to elaborate? I will submit a MR for it soon anyways.

**Comment by hadess** [comment]
It's explained in the tracking bug. But you should check beforehand whether file-roller actually needs to talk to gvfs or not. It will usually need that if it needs to list drives, or mount them.

**Comment by A6GibKm** [comment]
@hadess clearly the app does not mount/list drives, but I still don't know whats a clear way to tell if the app makes use of gvfs flags. I tried extracting something in a google drive folder but it seems it does not work. I think I will just remove the flags.
