### ISSUE TITLE
File-Roller supports official 7zip version (since 43.0)

### ISSUE THREAD

**Issue by ghost** [flathub/org.gnome.FileRoller#26]
Please make sure the Flatpak version of File Roller includes the official 7zip version. 

Talking with Jan Tojnar, he informed me that File-Roller already supports 7zip since version 43.0. Since he is not responsible for maintaining the Flatpak he asked me to open up a ticket regarding this issue.

Jan wrote this and I quote : " File-Roller already supports the official 7zip version (since 43.0,
https://gitlab.gnome.org/GNOME/file-roller/-/merge_requests/75). "

So can someone update the Flatpak manifest?

Regards,

Zookeeper

**Comment by A6GibKm** [comment]
Its already there https://github.com/flathub/org.gnome.FileRoller/blob/master/org.gnome.FileRoller.json#L20. Please reopen if there are issues.

**Comment by ghost** [comment]
Hello Maximiliano,

Thank you for getting back to me so fast.

Just a question I have. You replied that File Roller "Flatpak version" has had the 7zip integration complete in #20.

"url": "https://github.com/p7zip-project/p7zip/archive/refs/tags/v17.05.tar.gz",

When I look at the json file I see " p7zip version 17.05 " used. What I'm talking is having the official 7-zip binaries used from Igor Pavlov.

Am I missing something here?

Please be aware that I am not a programmer by trade.

Regards,

MO

Correct me if I'm w

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
