### ISSUE TITLE
Flatpak version has no Zstandard support

### ISSUE THREAD

**Issue by busukxuan** [flathub/org.gnome.FileRoller#6]
File Roller 3.36 seems to have support for Zstandard-compressed TARs (*.tar.zst). See https://gitlab.gnome.org/GNOME/file-roller/-/issues/41#note_739282. However, the Flatpak version seems unable to open this format properly. I suspect it's because there is no `zstd` tool inside the Flatpak sandbox. Would it be possible to package the `zstd` tool together with File Roller?

**Comment by A6GibKm** [comment]
Sure, please share any example of a file compressed with this standard.

**Comment by busukxuan** [comment]
Thanks for the swift patch, I can open my archive normally with the test build!

> Sure, please share any example of a file compressed with this standard.

I'm not sure how to share TARs on GitHub, but I believe pacman packages on Arch Linux's official repo are now in .tar.zst so you can find a bunch of example files there. Besides that, as you probably guessed, `tar` supports the `zstd` tool: `tar --zstd -cf outfile.tar.zst inpath`

Once again thanks for the swift patch!
